# Generated by Django 3.2.14 on 2022-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
